### PR TITLE
[TASK] Add compatibility with TYPO3 v13.0

### PR DESCRIPTION
**Pull request by peterkraume**

### CODE REVIEW

**Comment by liayn** [comment]
Peter, did you check (with rector or manually) whether all classes are really compatible?

**Comment by peterkraume** [comment]
Yes, I've checked that. Only problem is still this:
https://github.com/georgringer/t3monitoring_client/blob/master/Classes/Provider/StatusReportProvider.php#L34
But since the code is currently only relevant for TYPO3 < v12, I didn't tackle that problem.
Everything else is fine, Rector didn't find anything else to fix.
I run my fork already in production.

**Comment by liayn** [comment]
Perfect. Thanks!

**Comment by liayn** [comment]
I'll adjust the readme accordingly then

**Comment by peterkraume** [comment]
I would have written 13.4 straight away. My patch includes the LTS and breaking changes are no longer to be expected.

And I have one more request: is a new release possible? Then I can switch back to the official version in my project.

**Comment by liayn** [comment]
Feel free to push the stuff and we'll create a new release.

**Pull request merged**
